/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SystemTray {
  constructor(id?: string | undefined | null)
  id(): string
  setIcon(icon: string): void
  setTooltip(tooltip: string): void
  setTitle(title: string): void
  setVisible(visible: boolean): void
  setMenu(jsMenu: Menu): void
  listen(): void
  stop(): void
}

export interface Menu {
  items: Array<MenuItem>
}

export interface MenuItem {
  id?: string
  label?: string
  type?: 'normal' | 'separator' | 'submenu'
  enabled?: boolean
  submenu?: Array<MenuItem>
  callback?: () => void
}
